services:
  - type: web
    name: efootball-bot
    env: node
    plan: free
    buildCommand: npm install  # Install dependencies
    startCommand: node index.js  # Start the app using index.js, not app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIPHY_API_KEY
        value: ${GIPHY_API_KEY}  # Securely use environment variables
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}  # Securely use environment variables
    instanceClass: free
    disk:
      size: 512  # Optional: Adjust the disk size if necessary
